# Generated by Django 5.2.1 on 2025-05-20 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_nama_pengadu_alter_user_email_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instansi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi_laporan', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('masuk', 'Masuk'), ('valid', 'Valid'), ('tidak_valid', 'Tidak Valid'), ('diproses', 'Diproses'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='masuk', max_length=20)),
                ('instansi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.instansi')),
                ('pengadu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
