# Generated by Django 5.2.1 on 2025-05-20 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_instansi_laporan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laporan',
            name='instansi',
        ),
        migrations.RemoveField(
            model_name='laporan',
            name='pengadu',
        ),
        migrations.DeleteModel(
            name='Instansi',
        ),
        migrations.DeleteModel(
            name='Laporan',
        ),
    ]
