# Generated by Django 5.2.1 on 2025-05-28 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instansi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('isi', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='laporan_foto/')),
                ('status', models.CharField(choices=[('dalam_tinjauan', 'Dalam Tinjauan'), ('tidak_terverifikasi', 'Tidak Terverifikasi'), ('proses_tindaklanjut', 'Proses Tindaklanjut'), ('diberi_tanggapan', 'Diberi Tanggapan'), ('selesai', 'Selesai')], default='pending', max_length=20)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('instansi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pengaduan.instansi')),
                ('pelapor', models.ForeignKey(limit_choices_to={'role': 'pelapor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi_feedback', models.TextField()),
                ('tanggal_feedback', models.DateTimeField(auto_now_add=True)),
                ('pengirim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='pengaduan.laporan')),
            ],
        ),
    ]
